url: "https://www.olivercamilleri.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "https://www.olivercamilleri.co.uk" # the subpath of your site, e.g. /blog
title: "Oliver Camilleri" # the name of your site, e.g. ACME Corp.
description: "Computer Vision, Graphics, and Data-Driven Astronomy"
